data_path: "/storage1/fs1/sibai/Active/ihab/research_new/data_for_failure_classifier" # data path for data with labels
freeze_wm: True
single_layer_classifier: False
latent_dim: 512 # will calculate automatically in the next update
eval_freq: 10 # how often to evaluate the model during training
lr: 1e-4
weight_decay: 1e-5
batch_size: 128
epochs: 100
device: "cuda:0"
