data_path: "/storage1/fs1/sibai/Active/ihab/research_new/datasets_dino" # data path for data with labels
save_path: "/storage1/fs1/sibai/Active/ihab/research_new/checkpt_dino/classifier"
freeze_wm: True
# single_layer_classifier: False
with_proprio: True
latent_dim: 512 # will calculate automatically in the next update
eval_freq: 100 # how often to evaluate the model during training
lr: 1e-4
weight_decay: 1e-5
batch_size: 64
epochs: 2
device: "cuda:0"
seed: 0
gradient_penalty: True
gp_weight: 0.1
